name: TeamWorkflow

on:
  push:
    branches:
      - main


jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: Test
    container:
      image: node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: FTP delivery
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: test/todo/
          local-dir: dist/
        env:
          DEBUG: true

